"""
simulation/events.py – DES 시뮬레이션 이벤트 종류 코드

API·UI·event_log와 공통으로 사용하는 대문자 이벤트 코드.
"""
from typing import Dict, Tuple

EVENT_PROCESS_END = "PROCESS_END"
EVENT_MOVE_OUT = "MOVE_OUT"
EVENT_TOOL_RELEASE = "TOOL_RELEASE"
EVENT_WIP_INJECT = "WIP_INJECT"
EVENT_JOB_START = "JOB_START"
EVENT_CONV_START = "CONV_START"
EVENT_CONV_END = "CONV_END"
EVENT_TOOL_OCCUPY = "TOOL_OCCUPY"
EVENT_JOB_ASSIGNED = "JOB_ASSIGNED"

ALL_EVENT_KINDS: Tuple[str, ...] = (
    EVENT_PROCESS_END,
    EVENT_MOVE_OUT,
    EVENT_TOOL_RELEASE,
    EVENT_WIP_INJECT,
    EVENT_JOB_START,
    EVENT_CONV_START,
    EVENT_CONV_END,
    EVENT_TOOL_OCCUPY,
    EVENT_JOB_ASSIGNED,
)

# 동일 시각 이벤트 처리 순서 (작을수록 먼저)
EVENT_PRIORITY: Dict[str, int] = {
    EVENT_PROCESS_END: 0,
    EVENT_CONV_END:    1,
    EVENT_JOB_START:   10,
}
